# Render Infrastructure as Code
# Deploy Weave backend services (database already exists manually)

services:
  # FastAPI Web Service
  - type: web
    name: weave-api
    runtime: python
    region: oregon
    plan: starter  # or 'free' for testing
    rootDir: services/api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"

      - key: PORT
        value: "8000"

      # Database connection (set manually to link to existing weave-db)
      - key: DATABASE_URL
        sync: false  # Will be set manually in Render dashboard

      # OpenAI (you'll set this manually in dashboard for security)
      - key: OPENAI_API_KEY
        sync: false

      - key: EMBEDDING_MODEL
        value: text-embedding-3-small

      - key: EMBEDDING_DIM
        value: "1536"

      # JWT / Auth (you'll set these manually)
      - key: JWT_AUDIENCE
        value: weave

      - key: JWT_ISSUER
        sync: false

      - key: JWT_JWKS_URL
        sync: false

      # AWS S3 / Backblaze B2 (set manually for security)
      - key: AWS_ACCESS_KEY_ID
        sync: false

      - key: AWS_SECRET_ACCESS_KEY
        sync: false

      - key: AWS_S3_BUCKET
        sync: false

      - key: AWS_REGION
        value: us-east-1

      - key: S3_ENDPOINT_URL
        sync: false

      # CORS (update with your domains)
      - key: ALLOWED_ORIGINS
        value: https://chatgpt-ui-ivory.vercel.app,https://app.weweavee.com,https://weweavee.com

  # Background Worker for Indexing
  - type: worker
    name: weave-indexing-worker
    runtime: python
    region: oregon
    plan: starter  # or 'free' for testing
    rootDir: services/api
    buildCommand: pip install -r requirements.txt
    startCommand: python app/workers/indexing.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"

      # Database connection (set manually to link to existing weave-db)
      - key: DATABASE_URL
        sync: false  # Will be set manually in Render dashboard

      # OpenAI (you'll set this manually)
      - key: OPENAI_API_KEY
        sync: false

      - key: EMBEDDING_MODEL
        value: text-embedding-3-small

      - key: EMBEDDING_DIM
        value: "1536"
