name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (API) checks
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: weave
        ports: ["5432:5432"]
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r services/api/requirements.txt
          pip install -r services/api/requirements-dev.txt
      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 1
          done
      - name: Apply migrations
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d weave -f services/api/app/db/migrations/0001_init.sql
          psql -h localhost -U postgres -d weave -f services/api/app/db/migrations/0002_idempotency.sql
          psql -h localhost -U postgres -d weave -f services/api/app/db/migrations/0003_core_locked_at.sql
          psql -h localhost -U postgres -d weave -f services/api/app/db/migrations/0004_memory_event.sql
          psql -h localhost -U postgres -d weave -f services/api/app/db/rls.sql
      - name: Import check
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/weave
        run: |
          python - << 'PY'
          import importlib
          m = importlib.import_module('services.api.app.main'.replace('/', '.'))
          print('OK', m.app.title)
          PY
      - name: Ruff lint
        run: ruff check services/api/app
      - name: Pytest
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/weave
        run: pytest -q

  frontend:
    name: Frontend (UI) build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and build
        working-directory: apps/chatgpt-ui
        run: |
          npm ci || npm i
          npm run build
